<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Phalcon Tutorial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <?php echo $this->getContent(); ?>
</div>
</body>
</html>
<?php

echo $this->tag->linkTo(["signup", "Sign Up Here!", 'class' => 'btn btn-primary']);

if ($users->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>Name</th>
            <?php foreach ($users as $user) { ?>
                <td><?php echo $user->name; ?></td>
            <?php } ?>
        </tr>

        </thead>
        <tfoot>

        </tfoot>
        <tbody>
            <tr>
                <td colspan="3">Users quantity: <?php echo $users->count(); ?></td>
            </tr>
        </tbody>
    </table>
    <?php
}